In [3]:
import pandas as pd
import os

In [2]:
src_path = r'/home/dmacs/Documents/Final Dissertation/Data/Prices/Individual Collated/Excel/'
dest_path = r'/home/dmacs/Documents/Final Dissertation/Data/Prices/Individual Collated/StateWise_Aggregated/'

In [5]:
files = os.listdir(src_path)
files

['13_Soyabean.xlsx',
 '12_Mustard.xlsx',
 '1_Wheat.xlsx',
 '4_Maize.xlsx',
 '6_Bengal+Gram(Gram)(Whole).xlsx',
 '29_Barley_(Jau).xlsx',
 '263_Bengal_Gram_Dal_(Chana_Dal).xlsx']

In [50]:
filename = files[6]
filename

'263_Bengal_Gram_Dal_(Chana_Dal).xlsx'

In [51]:
df = pd.read_excel(src_path+filename)
df

,District Name,Market Name,Commodity,Variety,Grade,Min Price (Rs./Quintal),Max Price (Rs./Quintal),Modal Price (Rs./Quintal),Price Date,State
0,Prakasam,Giddalur,Bengal Gram Dal (Chana Dal),Other,Medium,4550,4650,4600,2015-12-24,Andhra Pradesh
1,Prakasam,Markapur,Bengal Gram Dal (Chana Dal),Other,Medium,8600,8700,8650,2016-11-28,Andhra Pradesh
2,Prakasam,Markapur,Bengal Gram Dal (Chana Dal),Other,Medium,8600,8700,8650,2016-11-27,Andhra Pradesh
3,Prakasam,Markapur,Bengal Gram Dal (Chana Dal),Other,Medium,5800,6000,5900,2016-07-26,Andhra Pradesh
4,Prakasam,Markapur,Bengal Gram Dal (Chana Dal),Other,Medium,5800,6000,5900,2016-07-22,Andhra Pradesh
...,...,...,...,...,...,...,...,...,...,...
58382,Howrah,Ramkrishanpur(Howrah),Bengal Gram Dal (Chana Dal),Bengal Gram Dal,FAQ,10400,10800,10600,2016-08-07,West Bengal
58383,Howrah,Ramkrishanpur(Howrah),Bengal Gram Dal (Chana Dal),Bengal Gram Dal,FAQ,10400,10800,10600,2016-08-06,West Bengal
58384,Howrah,Ramkrishanpur(Howrah),Bengal Gram Dal (Chana Dal),Bengal Gram Dal,FAQ,10400,10800,10600,2016-08-05,West Bengal
58385,Howrah,Ramkrishanpur(Howrah),Bengal Gram Dal (Chana Dal),Bengal Gram Dal,FAQ,10400,10800,10600,2016-08-04,West Bengal
58386,Howrah,Ramkrishanpur(Howrah),Bengal Gram Dal (Chana Dal),Bengal Gram Dal,FAQ,10400,10800,10600,2016-08-03,West Bengal

In [52]:
df['Price Date'] =  pd.to_datetime(df['Price Date'])
df['Yr-mon'] = df['Price Date'].dt.strftime('%Y%m')
df['Yr-mon'] = pd.to_datetime(df['Yr-mon'], format = '%Y%m')
df['Year'] = df.set_index('Yr-mon').index.year
df['Month'] = df.set_index('Yr-mon').index.month
df

,District Name,Market Name,Commodity,Variety,Grade,Min Price (Rs./Quintal),Max Price (Rs./Quintal),Modal Price (Rs./Quintal),Price Date,State,Yr-mon,Year,Month
0,Prakasam,Giddalur,Bengal Gram Dal (Chana Dal),Other,Medium,4550,4650,4600,2015-12-24,Andhra Pradesh,2015-12-01,2015,12
1,Prakasam,Markapur,Bengal Gram Dal (Chana Dal),Other,Medium,8600,8700,8650,2016-11-28,Andhra Pradesh,2016-11-01,2016,11
2,Prakasam,Markapur,Bengal Gram Dal (Chana Dal),Other,Medium,8600,8700,8650,2016-11-27,Andhra Pradesh,2016-11-01,2016,11
3,Prakasam,Markapur,Bengal Gram Dal (Chana Dal),Other,Medium,5800,6000,5900,2016-07-26,Andhra Pradesh,2016-07-01,2016,7
4,Prakasam,Markapur,Bengal Gram Dal (Chana Dal),Other,Medium,5800,6000,5900,2016-07-22,Andhra Pradesh,2016-07-01,2016,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58382,Howrah,Ramkrishanpur(Howrah),Bengal Gram Dal (Chana Dal),Bengal Gram Dal,FAQ,10400,10800,10600,2016-08-07,West Bengal,2016-08-01,2016,8
58383,Howrah,Ramkrishanpur(Howrah),Bengal Gram Dal (Chana Dal),Bengal Gram Dal,FAQ,10400,10800,10600,2016-08-06,West Bengal,2016-08-01,2016,8
58384,Howrah,Ramkrishanpur(Howrah),Bengal Gram Dal (Chana Dal),Bengal Gram Dal,FAQ,10400,10800,10600,2016-08-05,West Bengal,2016-08-01,2016,8
58385,Howrah,Ramkrishanpur(Howrah),Bengal Gram Dal (Chana Dal),Bengal Gram Dal,FAQ,10400,10800,10600,2016-08-04,West Bengal,2016-08-01,2016,8
58386,Howrah,Ramkrishanpur(Howrah),Bengal Gram Dal (Chana Dal),Bengal Gram Dal,FAQ,10400,10800,10600,2016-08-03,West Bengal,2016-08-01,2016,8

In [53]:
statewise_aggregated = df.groupby(['Yr-mon','State'],as_index = False).mean()

statewise_aggregated['Year'] = statewise_aggregated.set_index('Yr-mon').index.year
statewise_aggregated['Month'] = statewise_aggregated.set_index('Yr-mon').index.month
statewise_aggregated

,Yr-mon,State,Min Price (Rs./Quintal),Max Price (Rs./Quintal),Modal Price (Rs./Quintal),Year,Month
0,2012-05-01,Jharkhand,5000.000000,5533.333333,5300.000000,2012,5
1,2012-07-01,Jharkhand,5250.000000,5550.000000,5450.000000,2012,7
2,2012-08-01,Jharkhand,5500.000000,6000.000000,5775.000000,2012,8
3,2013-01-01,Jharkhand,5366.666667,5833.333333,5633.333333,2013,1
4,2013-03-01,Jharkhand,4200.000000,4800.000000,4500.000000,2013,3
...,...,...,...,...,...,...,...
645,2022-03-01,Madhya Pradesh,5476.900000,5765.500000,5598.100000,2022,3
646,2022-03-01,Maharashtra,5833.600000,6336.000000,6035.000000,2022,3
647,2022-03-01,Manipur,9947.540984,10655.737705,10301.639344,2022,3
648,2022-03-01,Uttar Pradesh,6238.204703,6416.445367,6326.334716,2022,3
649,2022-03-01,West Bengal,7300.000000,7700.000000,7500.000000,2022,3

In [54]:
dest_filename = filename.split('.')[0]
dest_filename

'263_Bengal_Gram_Dal_(Chana_Dal)'

In [55]:
statewise_aggregated.to_excel(dest_path+'{}_statewise_aggregated.xlsx'.format(dest_filename))